version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crosswork-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    expose:
      - 9000

  nginx:
    image: nginx:latest
    container_name: crosswork-nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - /Applications/XAMPP/xamppfiles/htdocs/crosswork/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: crosswork-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: crosswork
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
